routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name("index");

Route::get("register/teacher",["as" => "register.teacher" , "uses" => 'Auth\RegisterController@teacher']);

Route::get("register/enterprise",["as" => "register.enterprise" , "uses" => 'Auth\RegisterController@enterprise']);

Route::get("register/student",["as" => "register.student" , "uses" => 'Auth\RegisterController@student']);

Auth::routes();

Route::get('/home', ["as" => "home" , "uses" => 'HomeController@index',"middleware" => "auth" ]);


// RUTAS FUERA DE ADMIN

    //**ALUMNO**
Route::post("student/store",["as" => "student.store", "uses" => "StudentController@store"]);

    // **PROFESOR**
Route::post("teachers/store",["as" => "teacher.store", "uses" => "TeacherController@store"]);


    // **EMPRESA**
Route::post("enterprise/store",["as" => "enterprise.store", "uses" => "EnterpriseController@store"]);

    //  **USER**
Route::get("myoffers",["as"=>"user.myoffers","uses"=> "UserController@myoffers"])->middleware("auth");
Route::get("user/{user}",["as"=>"user.profile","uses"=> "UserController@profile"]);


    // **OFFER**
Route::get("offer/create",["as" => "offers.create", "uses" => "OfferController@create"])->middleware("rol:is_admin|is_enterprise");
Route::get("offers",["as" => "offers.index", "uses" => "OfferController@index"])->middleware("auth");
Route::get("offer/{offer}",["as" => "offers.show", "uses" => "OfferController@show"])->middleware("auth");
Route::get("offer/{offer}/edit",["as" => "offers.edit", "uses" => "OfferController@edit"])->middleware("rol:is_admin|is_enterprise");
Route::post("offer/store",["as" => "offers.store", "uses" => "OfferController@store"])->middleware("rol:is_admin|is_enterprise");
Route::put("offer/{offer}",["as" => "offers.update", "uses" => "OfferController@update"])->middleware("rol:is_admin|is_enterprise");
Route::delete("offer/{offer}",["as" => "offers.destroy", "uses" => "OfferController@destroy"])->middleware("rol:is_admin|is_enterprise");
Route::get("offer/{offer}/subscribe",["as" => "offers.subscribe", "uses" => "OfferController@subscribe"])->middleware("rol:is_student");
Route::get("offer/{offer}/unsubscribe",["as" => "offers.unsubscribe", "uses" => "OfferController@unsubscribe"])->middleware("rol:is_student");
Route::get("offer/{selection}/proffer",["as" => "offers.proffer", "uses" => "OfferController@proffer"])->middleware("rol:is_student");
Route::post("offer/{selection}/answer",["as" => "offers.answer", "uses" => "OfferController@answer"])->middleware("rol:is_student");

Route::group(["prefix" => "admin"], function () {



    Route::get("teacher/inactive",["as"=>"teacher.inactive","uses"=> "TeacherController@inactive"])->middleware("rol:is_admin");
    Route::get("enterprise/inactive",["as"=>"enterprise.inactive","uses"=> "EnterpriseController@inactive"])->middleware("rol:is_admin|is_teacher");
    Route::get("student/inactive",["as"=>"student.inactive","uses"=> "StudentController@inactive"])->middleware("rol:is_admin|is_teacher");
    Route::get("offers/inactive",["as"=>"offers.inactive","uses"=> "OfferController@inactive"]);

    Route::get("offer/{offer}/activate",["as" => "offers.activate", "uses" => "OfferController@activate"])->middleware("rol:is_admin|is_teacher");
    Route::post("offer/{offer}/assign",["as" => "offers.assign", "uses" => "OfferController@assign"])->middleware("rol:is_admin|is_teacher");
    Route::delete("offer/{selected}/selected",["as" => "offers.selected.destroy", "uses" => "OfferController@selectedDelete"])->middleware("rol:is_admin|is_teacher");

    //Route::resource('offers','OfferController');
    Route::put("user/toggle/active/{user}",["as"=>"user.toggle.active","uses"=> "UserController@changeActive"]);
    Route::post("user/toggle/active/selected",["as"=>"user.toggle.selected","uses"=> "UserController@changeSelected"]);
    Route::get("user/inactive",["as"=>"user.inactive","uses"=> "UserController@inactive"])->middleware("rol:is_admin|is_teacher");

    //Route::resource('enterprise', 'EnterpriseController');

    Route::get("enterprise",["as" => "enterprise.index", "uses" => "EnterpriseController@index"])->middleware("rol:is_admin|is_teacher");
    Route::get("enterprise/{enterprise}",["as" => "enterprise.show", "uses" => "EnterpriseController@show"])->middleware("rol:is_teacher","OneSelf");
    Route::get("enterprise/create",["as" => "enterprise.create", "uses" => "EnterpriseController@create"])->middleware("rol:is_admin|is_teacher");
    Route::get("enterprise/{enterprise}/edit",["as" => "enterprise.edit", "uses" => "EnterpriseController@edit"])->middleware("rol:is_admin|is_teacher","OneSelf");
    Route::delete("enterprise/{enterprise}",["as" => "enterprise.destroy", "uses" => "EnterpriseController@destroy"])->middleware("rol:is_admin","OneSelf");
    Route::put("enterprise/{enterprise}",["as" => "enterprise.update", "uses" => "EnterpriseController@update"])->middleware("rol:is_admin|is_teacher","OneSelf");


//    Route::resource('student', 'StudentController');

    Route::get("student/create",["as" => "student.create", "uses" => "StudentController@create"])->middleware("rol:is_admin|is_teacher");
    Route::get("student",["as" => "student.index", "uses" => "StudentController@index"])->middleware("rol:is_admin|is_teacher");
    Route::get("student/{student}",["as" => "student.show", "uses" => "StudentController@show"])->middleware("rol:is_admin|is_teacher");
    Route::get("student/{student}/edit",["as" => "student.edit", "uses" => "StudentController@edit"]);
    Route::delete("student/{student}",["as" => "student.destroy", "uses" => "StudentController@destroy"])->middleware("rol:is_admin","OneSelf");
    Route::put("student/{student}",["as" => "student.update", "uses" => "StudentController@update"])->middleware("rol:is_admin","OneSelf");
    Route::get("student",["as" => "student.index", "uses" => "StudentController@index"])->middleware("rol:is_admin|is_teacher");
    Route::post("student/{student}/cicle/add",["as" => "student.cicle.add", "uses" => "StudentController@newCicle"])->middleware("rol:is_admin");
    Route::delete("student/{student}/cicle/{cicle}",["as" => "student.cicle.destroy", "uses" => "StudentController@delCicle"])->middleware("rol:is_admin");
//    Route::resource('teacher', 'TeacherController');


    Route::get("teacher/create",["as" => "teacher.create", "uses" => "TeacherController@create"])->middleware("rol:is_admin");
    Route::get("teacher",["as" => "teacher.index", "uses" => "TeacherController@index"])->middleware("rol:is_admin|is_teacher");
    Route::get("teacher/{teacher}",["as" => "teacher.show", "uses" => "TeacherController@show"])->middleware("rol:is_admin|is_teacher","OneSelf");
    Route::get("teacher/{teacher}/edit",["as" => "teacher.edit", "uses" => "TeacherController@edit"])->middleware("OneSelf");
    Route::delete("teacher/{teacher}",["as" => "teacher.destroy", "uses" => "TeacherController@destroy"])->middleware("rol:is_admin","OneSelf");
    Route::put("teacher/{teacher}",["as" => "teacher.update", "uses" => "TeacherController@update"])->middleware("rol:is_admin","OneSelf");
    Route::post("teacher/{teacher}/cicle/add",["as" => "teacher.cicle.add", "uses" => "TeacherController@newCicle"])->middleware("rol:is_admin");
    Route::delete("teacher/{teacher}/cicle/{cicle}",["as" => "teacher.cicle.destroy", "uses" => "TeacherController@delCicle"])->middleware("rol:is_admin");

    Route::get("invitations",["as"=>"teacher.invitations","uses"=> "TeacherController@invitations"])->middleware("rol:is_admin");
    Route::delete("invitation/{invitation}/cancel",["as"=>"teacher.invitation.cancel","uses"=> "TeacherController@cancelInvitation"])->middleware("rol:is_admin");
    Route::post("teacher/invitations/clean",["as"=>"teacher.invitations.clean","uses"=> "TeacherController@cleanInvitations"])->middleware("rol:is_admin");
    Route::post("teacher/invite",["as"=>"teacher.invite","uses"=> "TeacherController@invite"])->middleware("rol:is_admin");


    Route::group(['middleware' => 'rol:is_admin'], function() { // ** Alguna otra forma de añadirle un middleware a un resource?? Refactorización si es mejorable **/
        Route::resource('family', 'FamilyController');
        Route::resource("cicle", 'CicleController');
    });
});

app/Cicle.php
<?php

/**
 * Modelo de Ciclos
 */

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

/**
 * Class Cicle
 *
 * Incluye las relaciones de los ciclos y filtros de búsqueda
 *
 * @package App
 */

class Cicle extends Model
{

    /**
     * Filliable
     *
     * Datos que Eloquent puede tratar sobre un objeto ciclo
     * @var array
     */
    protected $fillable = [
        'name', "plan", "tipo", "family_id", "created_at"
    ];

    /** RELACIONES **/

    /**
     * Relacion con familia
     *
     * Un ciclo pertenece a una familia
     * @return mixed
     */
    public function family()
    {
        return $this->belongsTo('App\Family');
    }

    //Relacion con teachers
    /**
     * Relación con profesores
     *
     * Un ciclo puede tener varios profesores
     * @return mixed
     */
    public function teachers()
    {
        return $this->belongsToMany('App\Teacher', 'cicle_teachers', 'cicle_id', 'teacher_id')->withTimestamps();
    }

    //Relacion con student

    /**
     * Relación con alumnos
     *
     * un ciclo puede pertenecer a varios alumnos
     * @return mixed
     */
    public function students()
    {
        return $this->belongsToMany('App\Student', 'student_courses', 'cicle_id', 'student_id');
    }






    /** SCOPES **/

    /**
     * Busqueda por nombre
     * @param $query hace referencia a la consulta, la cual se modifica con los datos siguientes
     * @param Request $request datos que introduce el usuario para activar la sentenencia de query.
     */
    public function scopeName($query, Request $request)
    {
        $name = $request->get("name");
        if (trim($name) != '') {
            $query->where('name', 'LIKE', "%$name%");
        }
    }
}

app/Http/Controllers/CicleController.php
<?php
/**
 * Controlador de Ciclos
 *
 * Este controlador permite la gestión de la informacón relativa a los Ciclos
 *
 *
 * @package App\Http\Controllers
 */

namespace App\Http\Controllers;


/**
 *
 * REQUEST
 *
 * Obtiene datos de formularios
 *
 */
use Illuminate\Http\Request;

/**
 *
 * Modelos
 *
 * Modelos usados
 *
 * @see App\Cicle;
 * @see App\Family;
 *
 */

use App\Cicle;
use App\Family;


/**
 *Sesión
 *
 * Variables de sessión
 * */
use Illuminate\Support\Facades\Session;

/**
 *
 *Class Cicle Controller
 *
 * Atiende las peticiones relativas a la gestión de Ciclos.
 *
 * @package App\Http\Controllers
 */

class CicleController extends Controller
{
    /**
     *  Muestra todos los ciclos ordenados.
     *
     * @param \Illuminate\Http\Request  $request  contiene un criterio para filtro.
     * @var App\Cicle $formatigeCicles ciclos formativos
     * @return void
     *
     */
    public function index(Request $request)
    {
        $formativeCicles = Cicle::Name($request)->get();

        return view("cicles.index",compact("formativeCicles","request"));
    }

    /**
     * Muesta el formulario para crear un nuevo ciclo
     *
     * @var App\Family $familys contiene todas las familias profesionales.
     * @return void
     *
     */
    public function create()
    {
        $familys = get_model_selectable_by_name(Family::all());
        return view('cicles.create',compact("familys"));
    }

    /**
     * Almacena un nuevo ciclo en bbdd
     *
     *
     * @param \Illuminate\Http\Request  $request   contiene la información del formulario del nuevo ciclo.
     * @var App\Cicle $cicle ciclo creado en base a los datos de entrada
     * @return  $cicle
     */
    public function store(Request $request)
    {
        $cicle_opts = [
            "nombre" => $request->get("name"),
            "tipo" => $request->get("tipo"),
            "plan" => $request->get("plan"),
            "family_id" => $request->get("family_id")
        ];
        $cicle = new Cicle($cicle_opts);
        $cicle->save();
        Session::flash('message', 'Ciclo Formativo agregado correctamente');
        return redirect()->route("cicle.index");
    }

    /**
     * Muestra la vista completa de un ciclo
     *
     * @param  \App\Cicle $cicle objeto con la información del ciclo solicitado.
     * @return void
     */
    public function show(Cicle $cicle)
    {
        //
        return view("cicles.show",compact("cicle"));
    }

    /**
     * Muesta el formulario para editar un ciclo
     *
     * @param  \App\Cicle  $cicle , datos del ciclo
     * @var \App\Family, $familys , datos de las familias profesionales.
     * return void
     */
    public function edit(Cicle $cicle)
    {
        $familys = get_model_selectable_by_name(Family::all());
        return view("cicles.edit",compact("cicle","familys"));
    }

    /**
     * Actualiza el ciclo en la bbdd
     *
     * @param  \Illuminate\Http\Request  $request datos recogidos del formulario
     * @param  \App\Cicle  $cicle  ciclo a editar.
     * @return $cicle
     */
    public function update(Request $request, Cicle $cicle)
    {
        $cicle->fill(["name" => $request->get("name"),"tipo"=>$request->get("tipo"),"plan"=>$request->get("plan")]);
        $cicle->save();
        Session::flash('message', 'Ciclo Profesional editado correctamente');
        return redirect()->route("cicle.index");
    }

    /**
     * Elimina el ciclo de la bbdd
     *
     * Utiliza la función soft delete, por lo que no se borra de la bbdd totalmente.
     *
     * @param  \App\Cicle  $cicle ciclo a ser borrado.
     * @return void
     */
    public function destroy(Cicle $cicle)
    {
        $name = $cicle->name;
        $cicle->delete();
        Session::flash('message', 'El ciclo formativo '.$name.' se ha eliminiado correctamente');
        return redirect()->route("cicle.index");
    }
}

resources/views/cicles/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="col-md-offset-5"> <h3>Nuevo Ciclo</h3></div>
                    </div>
                    <div class="panel-body">
                        {{ Form::open(['route' => 'cicle.store', 'method' => 'post' , 'class' => 'form']) }}
                            @include('cicles.partials.form')
                        <div class="form-group pull-right">
                            {{ Form::submit("Guardar",['class'=>'btn btn-success']) }}
                        </div>

                        {{ Form::close() }}
                        <div class="form-group pull-left">
                            <a href="{{route("cicle.index")}}" class="btn btn-default">Cancel</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cicles/edit.blade.php
@extends('layouts.layout')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h2 align="center">Editar</h2>
                        <h4 align="center">{{$cicle->name}}</h4>
                    </div>
                    <div class="panel-body">
                        {{Form::model($cicle, ['route' => ['cicle.update', $cicle->id],'method'=>'PUT'])}}
                            @include('cicles.partials.form')
                        <div class="form-group pull-right">
                            {{ Form::submit("Guardar",['class'=>'btn btn-success']) }}
                        </div>

                        {{ Form::close() }}
                        <div class="form-group pull-left">
                            <a href="{{route("cicle.index")}}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cicles/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="container-fluid">
        @include('cicles.partials.table')
    </div>
@endsection

resources/views/cicles/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 align="center">{{$cicle->name}}</h2>
                        <a href="{{route("cicle.edit",$cicle->id)}}" class="btn btn-info">Editar</a>
                    </div>
                    <div class="panel-body">
                        <div class="col-xs-12">
                            <a href="{{route("family.show",$cicle->family->id)}}">
                                <div class="panel panel-default">
                                    <h3 align="center">{{$cicle->family->name}}</h3>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="panel-footer">
                        <a class="btn btn-secondary pull-left" href="{{route("cicle.index")}}">Ir al Index</a>
                        <h5 align="right"><sup>Creado el: {{$cicle->created_at}}</sup></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection